import { 
  Tenant, 
  User, 
  UserRole, 
  MonitoredMailbox, 
  Incident, 
  ClientEntity, 
  TenantConfig, 
  ScreenPermissions, 
  TenantId,
  CommercialLead,
  QualityAuditRecord
} from '../types';

export const INITIAL_TENANTS: Tenant[] = [
  {
    id: 'contatur_sp',
    name: 'Contatur São Paulo',
    shortName: 'Contatur SP',
    city: 'São Paulo',
    uf: 'SP',
    cnpj: '12.345.678/0001-90',
    activeMailboxesCount: 18,
    monthlyRevenueTotal: 480000.0, // R$ 480 mil / mês
  },
  {
    id: 'contatur_rj',
    name: 'Contatur Rio',
    shortName: 'Contatur RJ',
    city: 'Rio de Janeiro',
    uf: 'RJ',
    cnpj: '12.345.678/0002-71',
    activeMailboxesCount: 14,
    monthlyRevenueTotal: 310000.0, // R$ 310 mil / mês
  },
  {
    id: 'mkp_sp',
    name: 'MKP São Paulo',
    shortName: 'MKP SP',
    city: 'São Paulo',
    uf: 'SP',
    cnpj: '98.765.432/0001-11',
    activeMailboxesCount: 12,
    monthlyRevenueTotal: 260000.0, // R$ 260 mil / mês
  },
];

export const FULL_PERMISSIONS: ScreenPermissions = {
  dashboard: { view: true, viewAllUnits: true, filterDepartment: true },
  incidents: {
    view: true,
    viewOnlyOwn: false,
    viewOnlyDepartment: false,
    changeStatus: true,
    assignUser: true,
    deleteOrArchive: true,
    useAiCopilot: true,
    sendDirectReply: true,
    sendPostServiceTouchpoint: true,
  },
  commercialOpportunities: { view: true, createProposal: true, changeStatus: true },
  monthlyBroadcasts: { view: true, approveSection: true, requestAiAdjustment: true, dispatchToClients: true },
  teamWorkload: { view: true, applyRebalancing: true },
  departmentDiagnosis: { view: true },
  qualityAudit: { view: true, exportAuditReport: true },
  unitBenchmark: { view: true },
  clientRadar: { view: true, editHealthScore: true, addRelationshipNote: true, scheduleMeeting: true },
  mailboxes: { view: true, toggleActive: true, triggerSync: true },
  settings: {
    view: true,
    editEmailProvider: true,
    editAiProvider: true,
    editAlertChannels: true,
    editSlaAndRules: true,
    editFiscalRules: true,
    editBroadcastRules: true,
    editMeetingIntegration: true,
  },
  users: { view: true, create: true, edit: true, delete: true, managePermissions: true },
  reports: { view: true, exportPdf: true, exportExcel: true },
};

export const UNIT_ADMIN_PERMISSIONS: ScreenPermissions = {
  dashboard: { view: true, viewAllUnits: false, filterDepartment: true },
  incidents: {
    view: true,
    viewOnlyOwn: false,
    viewOnlyDepartment: false,
    changeStatus: true,
    assignUser: true,
    deleteOrArchive: true,
    useAiCopilot: true,
    sendDirectReply: true,
    sendPostServiceTouchpoint: true,
  },
  commercialOpportunities: { view: true, createProposal: true, changeStatus: true },
  monthlyBroadcasts: { view: true, approveSection: true, requestAiAdjustment: true, dispatchToClients: true },
  teamWorkload: { view: true, applyRebalancing: true },
  departmentDiagnosis: { view: true },
  qualityAudit: { view: true, exportAuditReport: true },
  unitBenchmark: { view: true },
  clientRadar: { view: true, editHealthScore: true, addRelationshipNote: true, scheduleMeeting: true },
  mailboxes: { view: true, toggleActive: true, triggerSync: true },
  settings: {
    view: true,
    editEmailProvider: true,
    editAiProvider: true,
    editAlertChannels: true,
    editSlaAndRules: true,
    editFiscalRules: true,
    editBroadcastRules: true,
    editMeetingIntegration: true,
  },
  users: { view: true, create: true, edit: true, delete: true, managePermissions: true },
  reports: { view: true, exportPdf: true, exportExcel: true },
};

export const SUPERVISOR_PERMISSIONS: ScreenPermissions = {
  dashboard: { view: true, viewAllUnits: false, filterDepartment: true },
  incidents: {
    view: true,
    viewOnlyOwn: false,
    viewOnlyDepartment: true,
    changeStatus: true,
    assignUser: true,
    deleteOrArchive: false,
    useAiCopilot: true,
    sendDirectReply: true,
    sendPostServiceTouchpoint: true,
  },
  commercialOpportunities: { view: true, createProposal: true, changeStatus: false },
  monthlyBroadcasts: { view: true, approveSection: true, requestAiAdjustment: true, dispatchToClients: false },
  teamWorkload: { view: true, applyRebalancing: false },
  departmentDiagnosis: { view: true },
  qualityAudit: { view: true, exportAuditReport: false },
  unitBenchmark: { view: false },
  clientRadar: { view: true, editHealthScore: false, addRelationshipNote: true, scheduleMeeting: true },
  mailboxes: { view: true, toggleActive: false, triggerSync: false },
  settings: {
    view: false,
    editEmailProvider: false,
    editAiProvider: false,
    editAlertChannels: false,
    editSlaAndRules: false,
    editFiscalRules: false,
    editBroadcastRules: false,
    editMeetingIntegration: false,
  },
  users: { view: false, create: false, edit: false, delete: false, managePermissions: false },
  reports: { view: true, exportPdf: true, exportExcel: true },
};

export const ANALYST_PERMISSIONS: ScreenPermissions = {
  dashboard: { view: false, viewAllUnits: false, filterDepartment: false },
  incidents: {
    view: true,
    viewOnlyOwn: true,
    viewOnlyDepartment: false,
    changeStatus: true,
    assignUser: false,
    deleteOrArchive: false,
    useAiCopilot: true,
    sendDirectReply: false,
    sendPostServiceTouchpoint: false,
  },
  commercialOpportunities: { view: false, createProposal: false, changeStatus: false },
  monthlyBroadcasts: { view: false, approveSection: false, requestAiAdjustment: false, dispatchToClients: false },
  teamWorkload: { view: false, applyRebalancing: false },
  departmentDiagnosis: { view: false },
  qualityAudit: { view: false, exportAuditReport: false },
  unitBenchmark: { view: false },
  clientRadar: { view: true, editHealthScore: false, addRelationshipNote: false, scheduleMeeting: false },
  mailboxes: { view: false, toggleActive: false, triggerSync: false },
  settings: {
    view: false,
    editEmailProvider: false,
    editAiProvider: false,
    editAlertChannels: false,
    editSlaAndRules: false,
    editFiscalRules: false,
    editBroadcastRules: false,
    editMeetingIntegration: false,
  },
  users: { view: false, create: false, edit: false, delete: false, managePermissions: false },
  reports: { view: false, exportPdf: false, exportExcel: false },
};

export const DEFAULT_ROLES: UserRole[] = [
  {
    id: 'role_superadmin',
    name: 'SuperAdmin Global',
    description: 'Acesso irrestrito a todas as 3 empresas e a todas as telas e configurações.',
    permissions: FULL_PERMISSIONS,
  },
  {
    id: 'role_unit_admin',
    name: 'Administrador da Unidade',
    description: 'Acesso total de gestão e configuração exclusivamente para a unidade vinculada.',
    permissions: UNIT_ADMIN_PERMISSIONS,
  },
  {
    id: 'role_supervisor',
    name: 'Supervisor de Departamento',
    description: 'Gestão de ocorrências e acompanhamento de SLA da sua equipe setorial.',
    permissions: SUPERVISOR_PERMISSIONS,
  },
  {
    id: 'role_analyst',
    name: 'Analista de Atendimento',
    description: 'Tratamento de chamados atribuídos e uso do Copiloto de IA para minutas.',
    permissions: ANALYST_PERMISSIONS,
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_edson_superadmin',
    name: 'Edson Pereira (Diretoria)',
    email: 'edson@contatur.com.br',
    roleId: 'role_superadmin',
    roleName: 'SuperAdmin Global',
    tenantId: 'all',
    department: 'DIRETORIA',
    isActive: true,
    isSuperAdmin: true,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    phone: '(11) 99999-1000',
    permissions: FULL_PERMISSIONS,
    createdAt: '2026-01-01T08:00:00Z',
    lastLoginAt: '2026-08-18T13:20:00Z',
  },
  {
    id: 'usr_sp_gerente',
    name: 'Carlos Alberto Mendonça',
    email: 'carlos.gerencia@contatur.com.br',
    roleId: 'role_unit_admin',
    roleName: 'Administrador da Unidade',
    tenantId: 'contatur_sp',
    department: 'DIRETORIA',
    isActive: true,
    phone: '(11) 98765-4321',
    permissions: UNIT_ADMIN_PERMISSIONS,
    createdAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'usr_sp_fiscal',
    name: 'Mariana Souza (Fiscal SP)',
    email: 'mariana.fiscal@contatur.com.br',
    roleId: 'role_supervisor',
    roleName: 'Supervisor de Departamento',
    tenantId: 'contatur_sp',
    department: 'FISCAL',
    isActive: true,
    phone: '(11) 97654-3210',
    permissions: SUPERVISOR_PERMISSIONS,
    createdAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'usr_sp_analista_dp',
    name: 'Lucas Brandão (DP SP)',
    email: 'lucas.dp@contatur.com.br',
    roleId: 'role_analyst',
    roleName: 'Analista de Atendimento',
    tenantId: 'contatur_sp',
    department: 'FOLHA',
    isActive: true,
    phone: '(11) 96543-2109',
    permissions: ANALYST_PERMISSIONS,
    createdAt: '2026-02-10T11:00:00Z',
  },
  {
    id: 'usr_rj_gerente',
    name: 'Renata Vasconcellos',
    email: 'renata.gerencia@contatur-rio.com.br',
    roleId: 'role_unit_admin',
    roleName: 'Administrador da Unidade',
    tenantId: 'contatur_rj',
    department: 'DIRETORIA',
    isActive: true,
    phone: '(21) 98888-7777',
    permissions: UNIT_ADMIN_PERMISSIONS,
    createdAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'usr_rj_contabil',
    name: 'Felipe Meirelles (Contábil RJ)',
    email: 'felipe.contabil@contatur-rio.com.br',
    roleId: 'role_supervisor',
    roleName: 'Supervisor de Departamento',
    tenantId: 'contatur_rj',
    department: 'CONTABIL',
    isActive: true,
    phone: '(21) 97777-6666',
    permissions: SUPERVISOR_PERMISSIONS,
    createdAt: '2026-02-05T10:30:00Z',
  },
  {
    id: 'usr_mkp_gerente',
    name: 'Gustavo Paes',
    email: 'gustavo.gerencia@mkpcontabil.com.br',
    roleId: 'role_unit_admin',
    roleName: 'Administrador da Unidade',
    tenantId: 'mkp_sp',
    department: 'DIRETORIA',
    isActive: true,
    phone: '(11) 95555-4444',
    permissions: UNIT_ADMIN_PERMISSIONS,
    createdAt: '2026-01-20T08:30:00Z',
  },
];

export const INITIAL_MAILBOXES: MonitoredMailbox[] = [
  // Contatur SP
  {
    id: 'mb_sp_1',
    tenantId: 'contatur_sp',
    emailAddress: 'atendimento@contatur.com.br',
    displayName: 'Central de Atendimento Geral SP',
    department: 'GERAL',
    isActive: true,
    provider: 'm365',
    totalEmailsReceived: 1420,
    totalIncidentsFound: 14,
    lastSyncAt: '2026-08-18T13:25:00Z',
    status: 'ativo',
  },
  {
    id: 'mb_sp_2',
    tenantId: 'contatur_sp',
    emailAddress: 'fiscal@contatur.com.br',
    displayName: 'Departamento Fiscal SP',
    department: 'FISCAL',
    isActive: true,
    provider: 'm365',
    totalEmailsReceived: 2150,
    totalIncidentsFound: 19,
    lastSyncAt: '2026-08-18T13:26:00Z',
    status: 'ativo',
  },
  {
    id: 'mb_sp_3',
    tenantId: 'contatur_sp',
    emailAddress: 'folha@contatur.com.br',
    displayName: 'Departamento Pessoal & Folha SP',
    department: 'FOLHA',
    isActive: true,
    provider: 'm365',
    totalEmailsReceived: 1890,
    totalIncidentsFound: 8,
    lastSyncAt: '2026-08-18T13:27:00Z',
    status: 'ativo',
  },
  {
    id: 'mb_sp_4',
    tenantId: 'contatur_sp',
    emailAddress: 'contabil@contatur.com.br',
    displayName: 'Departamento Contábil SP',
    department: 'CONTABIL',
    isActive: true,
    provider: 'm365',
    totalEmailsReceived: 1120,
    totalIncidentsFound: 5,
    lastSyncAt: '2026-08-18T13:24:00Z',
    status: 'ativo',
  },
  {
    id: 'mb_sp_5',
    tenantId: 'contatur_sp',
    emailAddress: 'societario@contatur.com.br',
    displayName: 'Societário & Legalização SP',
    department: 'LEGAL',
    isActive: true,
    provider: 'm365',
    totalEmailsReceived: 630,
    totalIncidentsFound: 3,
    lastSyncAt: '2026-08-18T13:20:00Z',
    status: 'ativo',
  },
  {
    id: 'mb_sp_6',
    tenantId: 'contatur_sp',
    emailAddress: 'financeiro@contatur.com.br',
    displayName: 'Financeiro & Cobrança SP',
    department: 'FINANCEIRO',
    isActive: true,
    provider: 'm365',
    totalEmailsReceived: 880,
    totalIncidentsFound: 6,
    lastSyncAt: '2026-08-18T13:22:00Z',
    status: 'ativo',
  },
  {
    id: 'mb_sp_7',
    tenantId: 'contatur_sp',
    emailAddress: 'diretoria.sp@contatur.com.br',
    displayName: 'Diretoria & Sócios SP',
    department: 'DIRETORIA',
    isActive: true,
    provider: 'm365',
    totalEmailsReceived: 510,
    totalIncidentsFound: 4,
    lastSyncAt: '2026-08-18T13:20:00Z',
    status: 'ativo',
  },
  // Contatur Rio
  {
    id: 'mb_rj_1',
    tenantId: 'contatur_rj',
    emailAddress: 'atendimento@contatur-rio.com.br',
    displayName: 'Atendimento Geral Rio',
    department: 'GERAL',
    isActive: true,
    provider: 'm365',
    totalEmailsReceived: 950,
    totalIncidentsFound: 9,
    lastSyncAt: '2026-08-18T13:24:00Z',
    status: 'ativo',
  },
  {
    id: 'mb_rj_2',
    tenantId: 'contatur_rj',
    emailAddress: 'fiscal@contatur-rio.com.br',
    displayName: 'Setor Tributário & Fiscal Rio',
    department: 'FISCAL',
    isActive: true,
    provider: 'm365',
    totalEmailsReceived: 1410,
    totalIncidentsFound: 11,
    lastSyncAt: '2026-08-18T13:25:00Z',
    status: 'ativo',
  },
  {
    id: 'mb_rj_3',
    tenantId: 'contatur_rj',
    emailAddress: 'dp@contatur-rio.com.br',
    displayName: 'Folha & RH Rio',
    department: 'FOLHA',
    isActive: true,
    provider: 'm365',
    totalEmailsReceived: 1040,
    totalIncidentsFound: 4,
    lastSyncAt: '2026-08-18T13:26:00Z',
    status: 'ativo',
  },
  {
    id: 'mb_rj_4',
    tenantId: 'contatur_rj',
    emailAddress: 'diretoria.rj@contatur-rio.com.br',
    displayName: 'Diretoria & Sócios Rio',
    department: 'DIRETORIA',
    isActive: true,
    provider: 'm365',
    totalEmailsReceived: 420,
    totalIncidentsFound: 2,
    lastSyncAt: '2026-08-18T13:22:00Z',
    status: 'ativo',
  },
  // MKP SP
  {
    id: 'mb_mkp_1',
    tenantId: 'mkp_sp',
    emailAddress: 'contato@mkpcontabil.com.br',
    displayName: 'Contato Principal MKP',
    department: 'GERAL',
    isActive: true,
    provider: 'm365',
    totalEmailsReceived: 820,
    totalIncidentsFound: 5,
    lastSyncAt: '2026-08-18T13:21:00Z',
    status: 'ativo',
  },
  {
    id: 'mb_mkp_2',
    tenantId: 'mkp_sp',
    emailAddress: 'operacao@mkpcontabil.com.br',
    displayName: 'Operação & Tributos MKP',
    department: 'FISCAL',
    isActive: true,
    provider: 'm365',
    totalEmailsReceived: 1190,
    totalIncidentsFound: 7,
    lastSyncAt: '2026-08-18T13:23:00Z',
    status: 'ativo',
  },
  {
    id: 'mb_mkp_3',
    tenantId: 'mkp_sp',
    emailAddress: 'diretoria@mkpcontabil.com.br',
    displayName: 'Diretoria & Sócios MKP',
    department: 'DIRETORIA',
    isActive: true,
    provider: 'm365',
    totalEmailsReceived: 380,
    totalIncidentsFound: 3,
    lastSyncAt: '2026-08-18T13:20:00Z',
    status: 'ativo',
  },
];

export const INITIAL_CLIENTS: ClientEntity[] = [
  {
    id: 'cli_1',
    tenantId: 'contatur_sp',
    name: 'TechLog Transportes e Logística LTDA',
    cnpjCpf: '18.444.921/0001-30',
    type: 'CLIENTE',
    contactEmails: ['roberto@techlog.com.br', 'financeiro@techlog.com.br'],
    primaryDepartment: 'FISCAL',
    monthlyFee: 14500.0,
    curveABC: 'A',
    healthScore: 38,
    statusRelacionamento: 'Crítico',
    ghostingStatus: 'NORMAL',
    interactionDropPercentage: 0,
    lastEmailReceivedDate: '2026-08-18',
    totalIncidentsCount: 4,
    criticalIncidentsCount: 2,
    lastIncidentDate: '2026-08-18',
    notes: [
      '18/08: Intimação de DCTFWeb e ameaça de rescisão contratual. Honorário de R$ 14.500 sob risco imediato.',
      '12/07: Reclamação anterior de atraso na apuração de ICMS DIFAL.'
    ]
  },
  {
    id: 'cli_2',
    tenantId: 'contatur_sp',
    name: 'Metalúrgica Alvorada Paulista S.A.',
    cnpjCpf: '03.882.114/0001-88',
    type: 'CLIENTE',
    contactEmails: ['juliana.rh@alvoradametal.com.br', 'diretoria@alvoradametal.com.br'],
    primaryDepartment: 'FOLHA',
    monthlyFee: 19800.0,
    curveABC: 'A',
    healthScore: 68,
    statusRelacionamento: 'Em Risco',
    ghostingStatus: 'ATENCAO_QUEDA_INTERACAO',
    interactionDropPercentage: 45,
    lastEmailReceivedDate: '2026-08-18',
    totalIncidentsCount: 3,
    criticalIncidentsCount: 0,
    lastIncidentDate: '2026-08-18',
    notes: [
      '18/08: Divergência nos cálculos de horas extras e adicional noturno. Queda de 45% nas mensagens.'
    ]
  },
  {
    id: 'cli_3',
    tenantId: 'contatur_sp',
    name: 'Grupo FarmaLife Distribuidora',
    cnpjCpf: '11.222.333/0001-99',
    type: 'CLIENTE',
    contactEmails: ['diretoria@farmalife.com.br'],
    primaryDepartment: 'FISCAL',
    monthlyFee: 24000.0,
    curveABC: 'A',
    healthScore: 49,
    statusRelacionamento: 'Crítico',
    ghostingStatus: 'CRITICO_GHOSTING',
    interactionDropPercentage: 82,
    lastEmailReceivedDate: '2026-07-28',
    totalIncidentsCount: 2,
    criticalIncidentsCount: 1,
    lastIncidentDate: '2026-07-28',
    notes: [
      '18/08: Alerta de Silêncio (Ghosting)! Cliente reduziu 82% das interações há 21 dias. Alto risco de troca de contador.'
    ]
  },
  {
    id: 'cli_4',
    tenantId: 'contatur_rj',
    name: 'Guanabara Gourmet Restaurante e Eventos',
    cnpjCpf: '22.111.333/0001-44',
    type: 'CLIENTE',
    contactEmails: ['marcio@guanabaragourmet.com.br'],
    primaryDepartment: 'LEGAL',
    monthlyFee: 8500.0,
    curveABC: 'B',
    healthScore: 52,
    statusRelacionamento: 'Em Risco',
    ghostingStatus: 'NORMAL',
    interactionDropPercentage: 0,
    lastEmailReceivedDate: '2026-08-18',
    totalIncidentsCount: 2,
    criticalIncidentsCount: 0,
    lastIncidentDate: '2026-08-18',
    notes: [
      '18/08: Reclamação sobre prazo de alteração na JUCERJA impactando conta bancária.'
    ]
  },
  {
    id: 'cli_5',
    tenantId: 'mkp_sp',
    name: 'Smart Varejo e Distribuição EIRELI',
    cnpjCpf: '45.678.910/0001-22',
    type: 'CLIENTE',
    contactEmails: ['tatiane@smartvarejo.com.br'],
    primaryDepartment: 'FISCAL',
    monthlyFee: 12000.0,
    curveABC: 'A',
    healthScore: 42,
    statusRelacionamento: 'Crítico',
    ghostingStatus: 'NORMAL',
    interactionDropPercentage: 0,
    lastEmailReceivedDate: '2026-08-18',
    totalIncidentsCount: 3,
    criticalIncidentsCount: 1,
    lastIncidentDate: '2026-08-18',
    notes: [
      '18/08: Guia do Simples Nacional duplicada por falta de segregação de ICMS ST.'
    ]
  }
];

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: 'inc_sp_101',
    tenantId: 'contatur_sp',
    mailboxId: 'mb_sp_2',
    mailboxEmail: 'fiscal@contatur.com.br',
    messageId: 'MSG-2026-0818-0914',
    senderName: 'Roberto Silveira (CEO TechLog Transportes)',
    senderEmail: 'roberto@techlog.com.br',
    senderType: 'CLIENTE',
    recipientEmail: 'fiscal@contatur.com.br',
    subject: 'URGENTE: Notificação de Multa da Receita por atraso na DCTFWeb e falta de retorno',
    emailBodyText: `Prezados,\n\nRecebemos hoje uma intimação com auto de infração da Receita Federal referente ao atraso na entrega da DCTFWeb do mês passado. Estou tentando falar com o analista responsável desde ontem por telefone e ninguém atende ou retorna.\n\nIsso é inadmissível! Se essa multa não for justificada ou cancelada imediatamente, iremos acionar nosso departamento jurídico e rescindir o contrato de prestação de serviços com a Contatur.\n\nExijo retorno urgente da gerência ainda hoje.`,
    receivedAt: '2026-08-18T09:14:00Z',
    
    // Inovação 7: Anexos Processados com OCR
    attachments: [
      {
        fileName: 'Intimacao_Receita_Federal_Auto_88291.pdf',
        type: 'PRINT_OCR',
        extractedText: 'MINISTÉRIO DA FAZENDA - RECEITA FEDERAL DO BRASIL. AUTO DE INFRAÇÃO Nº 88291/2026. SUJEITO PASSIVO: TECHLOG TRANSPORTES. PENALIDADE: MULTA POR ATRASO NA ENTREGA DA DCTFWEB COMPETÊNCIA 07/2026 NO VALOR DE R$ 1.500,00.',
        confidenceScore: 99.4,
      },
    ],

    // Inovação 4: Alerta de Calendário Fiscal
    fiscalAlert: {
      obligationName: 'DCTFWeb',
      dueDate: '2026-08-15',
      daysRemaining: -3,
      isUrgentPromotion: true,
    },

    sentimentScore: -0.92,
    severity: 'CRITICAL',
    category: 'FISCAL',
    aiSummary: 'Cliente relata recebimento de auto de infração da Receita Federal por atraso na DCTFWeb, reclama de falta de retorno e ameaça rescisão contratual imediata e acionamento jurídico. Honorário de R$ 14.500/mês sob risco.',
    riskReasoning: 'Sentimento extremamente negativo com menção explícita a cancelamento de contrato, processo judicial e prejuízo financeiro com multa fiscal.',
    highlightedPhrases: [
      { text: 'intimação com auto de infração da Receita Federal', reason: 'Prejuízo fiscal e erro de obrigação acessória', impact: 'severo' },
      { text: 'ninguém atende ou retorna', reason: 'Falta de atendimento/SLA violado', impact: 'moderado' },
      { text: 'iremos acionar nosso departamento jurídico e rescindir o contrato', reason: 'Ameaça explícita de perda de cliente', impact: 'severo' }
    ],
    suggestedReply: `Prezado Roberto, bom dia.\n\nRecebemos sua mensagem com a máxima prioridade e lamentamos profundamente o transtorno causado.\n\nNossa gerência tributária e a diretoria já assumiram o caso pessoalmente neste momento. Estamos auditando o protocolo de transmissão da DCTFWeb para verificar a divergência e, caso tenha havido qualquer inconsistência por nossa parte, assumiremos integralmente as providências cabíveis sem qualquer ônus para a TechLog.\n\nNosso gerente tributário entrará em contato com o senhor por telefone nos próximos 15 minutos para posicioná-lo sobre o protocolo retificador.`,
    suggestedActionPlan: [
      '1. Baixar o recibo de transmissão da DCTFWeb no e-CAC e comparar com a intimação.',
      '2. Gerente ligar imediatamente para o cliente Roberto Silveira.',
      '3. Se houve erro do sistema, protocolar impugnação/retificação e gerar termo de assunção de responsabilidade.'
    ],
    
    // Inovação 6: Touchpoint Pós-Atendimento
    postServiceTouchpointScheduled: true,
    postServiceTouchpointDraft: 'Olá Roberto, bom dia. Nossa diretoria acompanhou a resolução da retificação da sua DCTFWeb e a baixa do auto de infração junto à Receita. Gostaria de confirmar se sua operação está 100% regularizada e nos colocar à disposição para qualquer suporte!',

    churnRiskScore: 94,
    status: 'NOVO',
    assignedToUserId: 'usr_sp_fiscal',
    assignedToUserName: 'Mariana Souza (Fiscal SP)',
    slaDeadline: '2026-08-18T11:14:00Z',
    isSlaViolated: true,
    history: [
      {
        id: 'hist_1',
        type: 'criacao',
        authorName: 'IA Sentinel (Monitor M365 + OCR Engine)',
        description: 'Incidente crítico detectado com OCR no PDF da Receita Federal. Alerta financeiro: Honorário de R$ 14.500/mês sob risco.',
        timestamp: '2026-08-18T09:14:30Z'
      }
    ]
  },
  {
    id: 'inc_sp_102',
    tenantId: 'contatur_sp',
    mailboxId: 'mb_sp_3',
    mailboxEmail: 'folha@contatur.com.br',
    messageId: 'MSG-2026-0818-1030',
    senderName: 'Juliana Prado (RH Metalúrgica Alvorada)',
    senderEmail: 'juliana.rh@alvoradametal.com.br',
    senderType: 'CLIENTE',
    recipientEmail: 'folha@contatur.com.br',
    subject: 'Inconsistência nos holerites e cálculo errado de horas extras',
    emailBodyText: `Olá Lucas,\n\nVerificamos os holerites enviados para o fechamento deste mês e o cálculo do adicional noturno e horas extras de três funcionários veio divergente do espelho de ponto que encaminhamos no dia 05.\n\nPrecisamos rodar o pagamento amanhã pela manhã. Por favor, reemitam os recibos e as guias com urgência para não termos problemas com os colaboradores.`,
    receivedAt: '2026-08-18T10:30:00Z',
    
    // Inovação 7: Áudio Transcrito
    attachments: [
      {
        fileName: 'Audio_WhatsApp_Juliana_RH.ogg',
        type: 'AUDIO_TRANSCRIPTION',
        extractedText: 'Oi Lucas, é a Juliana da Alvorada. Pelo amor de Deus, ajusta esses três holerites porque os encarregados da fábrica estão na minha porta cobrando o pagamento certo de amanhã!',
        confidenceScore: 97.8,
      }
    ],

    fiscalAlert: {
      obligationName: 'FGTS Digital & Folha',
      dueDate: '2026-08-20',
      daysRemaining: 2,
      isUrgentPromotion: true,
    },

    sentimentScore: -0.65,
    severity: 'HIGH',
    category: 'FOLHA',
    aiSummary: 'Cliente identificou cálculo divergente de adicional noturno e horas extras nos holerites antes do dia de pagamento e solicita reemissão urgente. Honorário de R$ 19.800/mês.',
    riskReasoning: 'Risco de atrito trabalhista para o cliente caso o pagamento saia incorreto. Tom de cobrança firme com prazo curto (amanhã).',
    highlightedPhrases: [
      { text: 'cálculo do adicional noturno e horas extras (...) veio divergente', reason: 'Inconsistência em cálculo de folha', impact: 'severo' },
      { text: 'Precisamos rodar o pagamento amanhã pela manhã', reason: 'Prazo crítico', impact: 'moderado' }
    ],
    suggestedReply: `Olá Juliana, bom dia.\n\nJá identificamos o e-mail e o áudio com os espelhos do dia 05 e estamos reprocessando os cálculos de horas extras e adicional noturno desses três colaboradores imediatamente.\n\nEm até 1 hora encaminharemos os holerites retificados e o arquivo bancário atualizado para que seu cronograma de pagamento não seja afetado.`,
    suggestedActionPlan: [
      '1. Recalcular eventos 101 (HE) e 105 (Adic. Noturno) no sistema de folha.',
      '2. Reenviar espelhos corrigidos e relatório de conferência.',
      '3. Reemitir guia de FGTS Digital caso haja diferença de base.'
    ],
    churnRiskScore: 68,
    status: 'EM_TRATAMENTO',
    assignedToUserId: 'usr_sp_analista_dp',
    assignedToUserName: 'Lucas Brandão (DP SP)',
    slaDeadline: '2026-08-18T14:30:00Z',
    isSlaViolated: false,
    history: [
      {
        id: 'hist_2',
        type: 'criacao',
        authorName: 'IA Sentinel (Transcrição de Áudio)',
        description: 'Detectada reclamação de divergência de folha com áudio transcrito do cliente.',
        timestamp: '2026-08-18T10:30:15Z'
      }
    ]
  }
];

// Inovação 2: Leads Comerciais / Cross-Selling Detectados pela IA
export const INITIAL_COMMERCIAL_LEADS: CommercialLead[] = [
  {
    id: 'lead_1',
    tenantId: 'contatur_sp',
    clientName: 'Metalúrgica Alvorada Paulista S.A.',
    clientCnpj: '03.882.114/0001-88',
    opportunityType: 'ABERTURA_FILIAL',
    title: 'Abertura de Filial em Campinas/SP (Expansão)',
    detectedTextSnippet: 'Estamos fechando o galpão para a nossa nova filial logística em Campinas no mês que vem e vamos precisar providenciar o CNPJ e alvarás...',
    estimatedMonthlyValue: 3500.0, // R$ 3.500 a mais por mês
    confidenceScore: 96,
    aiProposalDraft: `Prezada Juliana / Diretoria da Metalúrgica Alvorada,\n\nIdentificamos a excelente notícia da expansão da Alvorada com a nova unidade em Campinas/SP!\n\nNossa equipe especializada do departamento Societário & Legalização da Contatur SP preparou uma proposta completa para conduzir 100% da abertura da filial na JUCESP, emissão do CNPJ, Inscrição Estadual e obtenção dos alvarás municipais com máxima agilidade e economia tributária.\n\nGostaria de agendar uma breve conferência com nosso gerente de legalização?`,
    status: 'NOVO',
    detectedAt: '2026-08-18T11:45:00Z',
  },
  {
    id: 'lead_2',
    tenantId: 'contatur_sp',
    clientName: 'TechLog Transportes e Logística LTDA',
    clientCnpj: '18.444.921/0001-30',
    opportunityType: 'AUMENTO_QUADRO_FOLHA',
    title: 'Admissão de 40 Novos Motoristas (Revisão de Faixa)',
    detectedTextSnippet: 'Ganhamos um novo contrato de distribuição e iremos contratar cerca de 40 motoristas CLT a partir do dia 1º...',
    estimatedMonthlyValue: 2800.0,
    confidenceScore: 92,
    aiProposalDraft: `Prezado Roberto, parabéns pelo novo contrato de distribuição da TechLog!\n\nPara absorver com total segurança as 40 novas admissões e a gestão do eSocial/FGTS Digital desse novo contingente, preparamos o aditivo de serviços com condições operacionais sob medida para sua frota.`,
    status: 'EM_PROPOSTA',
    detectedAt: '2026-08-17T16:20:00Z',
  },
  {
    id: 'lead_3',
    tenantId: 'contatur_rj',
    clientName: 'Guanabara Gourmet Restaurante e Eventos',
    clientCnpj: '22.111.333/0001-44',
    opportunityType: 'BPO_FINANCEIRO',
    title: 'Terceirização do Contas a Pagar & Conciliação (BPO)',
    detectedTextSnippet: 'Estamos tendo muita dificuldade em conciliar os recebimentos de cartão e fechar as contas a pagar da semana...',
    estimatedMonthlyValue: 4200.0,
    confidenceScore: 89,
    aiProposalDraft: `Prezado Marcio, temos uma solução ideal para eliminar a sobrecarga financeira do restaurante: nosso serviço de BPO Financeiro Contatur Rio (gestão de contas a pagar, conciliação diária de adquirentes e relatórios de fluxo de caixa em tempo real).`,
    status: 'NOVO',
    detectedAt: '2026-08-18T09:30:00Z',
  },
];

// Inovação 5: Registros de Auditoria de Qualidade de Respostas dos Analistas
export const INITIAL_QUALITY_AUDITS: QualityAuditRecord[] = [
  {
    id: 'aud_1',
    tenantId: 'contatur_sp',
    incidentId: 'inc_sp_102',
    analystName: 'Lucas Brandão',
    analystEmail: 'lucas.dp@contatur.com.br',
    department: 'FOLHA',
    clientEmail: 'juliana.rh@alvoradametal.com.br',
    replyTextAudited: 'Juliana, nós já recalculamos os holerites e estamos enviando em anexo. Pedimos desculpas pela divergência no fechamento do ponto.',
    toneClassification: 'Excelente / Empático',
    qualityScore: 95,
    aiFeedback: 'Resposta rápida, tom cortês, reconhecimento do problema e solução enviada dentro do prazo.',
    flaggedPhrases: [],
    auditedAt: '2026-08-18T11:15:00Z',
  },
  {
    id: 'aud_2',
    tenantId: 'contatur_sp',
    incidentId: 'inc_sp_old_99',
    analystName: 'Analista Júnior Teste',
    analystEmail: 'junior.fiscal@contatur.com.br',
    department: 'FISCAL',
    clientEmail: 'cliente@exemplo.com.br',
    replyTextAudited: 'Isso não é com o fiscal, já falei que você tem que pedir pro seu financeiro ver o comprovante.',
    toneClassification: 'Ríspido / Inadequado',
    qualityScore: 32,
    aiFeedback: 'Tom agressivo e evasivo. Transferência de responsabilidade ao cliente sem orientação adequada.',
    flaggedPhrases: ['já falei que você tem que pedir', 'Isso não é com o fiscal'],
    auditedAt: '2026-08-17T14:20:00Z',
  },
];

export const INITIAL_TENANT_CONFIGS: Record<TenantId, TenantConfig> = {
  contatur_sp: {
    tenantId: 'contatur_sp',
    email: {
      provider: 'm365',
      m365: {
        tenantId: 'contatur-sp-azure-tenant-id-8832',
        clientId: 'contatur-sp-app-client-id-4421',
        clientSecret: '••••••••••••••••••••••••••••••••',
        adminEmail: 'admin.ti@contatur.com.br',
      },
      googleWorkspace: {
        adminEmail: 'admin@contatur.com.br',
        serviceAccountJson: '{\n  "type": "service_account",\n  "project_id": "contatur-sp-workspace"\n}',
        delegatedSubject: 'admin@contatur.com.br',
      },
      imap: {
        host: 'mail.contatur.com.br',
        port: 993,
        useSsl: true,
        user: 'monitoramento@contatur.com.br',
        pass: '••••••••••••',
      },
      syncIntervalMinutes: 5,
      monitorBoardOfDirectors: true,
      lastTestedAt: '2026-08-18T13:20:00Z',
      connectionStatus: 'conectado',
    },
    ai: {
      provider: 'gemini',
      apiKey: 'AIzaSyDemoContaturSPKey_88329910248239',
      model: 'gemini-1.5-flash',
      temperature: 0.2,
      systemPrompt: `Você é o Auditor de Sentimento e Atendimento Especialista da CONTATUR SÃO PAULO.
Analise e-mails de clientes e fornecedores identificando:
1. Sentimento e risco de churn
2. Oportunidades comerciais (abertura de filiais, novos funcionários, BPO)
3. Auditoria do tom de respostas dos analistas
4. Risco de calendário fiscal (DCTFWeb, DAS, FGTS).`,
      minConfidenceScore: 75,
      enableCommercialDetection: true,
      enableQualityAuditing: true,
      enableOcrAndAudioTranscription: true,
      lastTestedAt: '2026-08-18T13:20:00Z',
    },
    alertChannels: {
      emailNotifications: {
        enabled: true,
        destinationEmails: ['diretoria.sp@contatur.com.br', 'gerencia.sp@contatur.com.br'],
        sendOnCritical: true,
        sendOnHigh: true,
        sendOnCommercialLead: true,
      },
      msTeams: {
        enabled: true,
        webhookUrl: 'https://contatur.webhook.office.com/webhookb2/sp-incidentes-criticos',
        sendOnCritical: true,
        sendOnHigh: true,
        sendOnCommercialLead: true,
      },
      whatsapp: {
        enabled: true,
        apiEndpoint: 'https://api.z-api.io/instances/contatur-sp/token/sendMessage',
        apiToken: '••••••••••••••••••••••••••••••••',
        destinationNumbers: ['5511999991000', '5511987654321'],
        sendOnCritical: true,
        sendOnHigh: false,
      },
      discord: { enabled: false, webhookUrl: '', sendOnCritical: false },
      telegram: { enabled: false, botToken: '', chatId: '', sendOnCritical: false },
    },
    supervisorWorkflow: {
      enabled: true,
      autoSendWelcomeEmail: false, // Requer aprovação com 1 clique do supervisor
      welcomeEmailTemplate: `Prezado(a) {CLIENTE_NOME},\n\nSou {SUPERVISOR_NOME}, supervisor do setor {DEPARTAMENTO} da Contatur São Paulo.\n\nIdentificamos sua mensagem referente a "{ASSUNTO}" (Protocolo #{PROTOCOLO}) e estou assumindo pessoalmente o acompanhamento do seu caso para garantir total prioridade e agilidade na resolução.\n\nNossa equipe já está analisando o histórico e entraremos em contato com a solução técnica definitiva.\n\nAtenciosamente,\n{SUPERVISOR_NOME}\nSupervisão {DEPARTAMENTO} &bull; Contatur São Paulo`,
      statusUpdateTemplate: `Prezado(a) {CLIENTE_NOME},\n\nInformamos que seu chamado #{PROTOCOLO} está em fase de {STATUS_ATUAL}. Nosso analista responsável está concluindo a verificação e você receberá o retorno conclusivo em breve.`,
      csatEmailTemplate: `Prezado(a) {CLIENTE_NOME},\n\nSua solicitação #{PROTOCOLO} foi concluída com sucesso por nossa equipe. Para continuarmos aprimorando nosso padrão de atendimento, como você avalia a solução apresentada?`,
      escalateToDirectorHours: 2,
    },
    sgcIntegration: {
      enabled: true,
      baseUrl: 'https://sgc.grupocontaturmkp.com.br/api/external/v1',
      apiToken: 'sgc_sec_contatur_sp_9921482012',
      autoPushLeads: false,
      lastTestedAt: '2026-08-18T14:00:00Z',
      connectionStatus: 'conectado',
    },
    meetingIntegration: {
      enabled: true,
      baseUrl: 'https://meeting.grupocontaturmkp.com.br/api/external/v1',
      apiToken: 'meeting_sec_contatur_sp_778811',
      autoInjectDossierInAgenda: true,
      defaultMeetingLocation: 'Sala da Diretoria SP / Microsoft Teams',
      lastTestedAt: '2026-08-18T14:00:00Z',
      connectionStatus: 'conectado',
    },
    monthlyBroadcastSettings: {
      enabled: true,
      targetAudienceProfile: 'Turismo, Hotelaria & Eventos',
      dispatchDayOfMonth: 25,
      autoDispatchWhenAllApproved: false,
      supervisors: {
        folha: { name: 'Lucas Brandão', email: 'lucas.dp@contatur.com.br' },
        fiscal: { name: 'Mariana Souza', email: 'mariana.fiscal@contatur.com.br' },
        contabil: { name: 'Julio Cesar', email: 'julio.contabil@contatur.com.br' },
        legal: { name: 'Renata Castro', email: 'societario@contatur.com.br' },
      },
      approvalRequestEmailTemplate: `Prezado(a) Supervisor(a) {SUPERVISOR_NOME},\n\nA IA do Contatur Sentinel gerou a proposta da Circular Legislativa Mensal para o setor de {DEPARTAMENTO} (Edição {MES_ANO}).\n\nPor favor, revise o texto técnico no link abaixo e aprove ou solicite novos ajustes:\n{LINK_APROVACAO}\n\nContatur Sentinel • Inteligência Corporativa`,
    },
    slaAndRules: {
      slaHoursCritical: 2,
      slaHoursHigh: 4,
      slaHoursMedium: 12,
      slaHoursLow: 24,
      autoPromoteNearFiscalDeadline: true,
      touchpointDelayHours: 48,
      blacklistKeywords: ['newsletter', 'promoção', 'cupom', 'webinar', 'no-reply', 'linkedin', 'github'],
      priorityKeywords: ['multa', 'receita federal', 'sefaz', 'processo', 'rescisão', 'cancelar contrato', 'procon', 'inadmissível', 'jurídico', 'urgente'],
      autoIgnoreSpamAndNewsletters: true,
    },
  },
  contatur_rj: {
    tenantId: 'contatur_rj',
    email: {
      provider: 'm365',
      m365: {
        tenantId: 'contatur-rj-azure-tenant-id-1102',
        clientId: 'contatur-rj-app-client-id-9931',
        clientSecret: '••••••••••••••••••••••••••••••••',
        adminEmail: 'admin.ti@contatur-rio.com.br',
      },
      googleWorkspace: {
        adminEmail: 'admin@contatur-rio.com.br',
        serviceAccountJson: '',
        delegatedSubject: '',
      },
      imap: {
        host: 'mail.contatur-rio.com.br',
        port: 993,
        useSsl: true,
        user: 'monitoramento@contatur-rio.com.br',
        pass: '',
      },
      syncIntervalMinutes: 5,
      monitorBoardOfDirectors: true,
      lastTestedAt: '2026-08-18T13:22:00Z',
      connectionStatus: 'conectado',
    },
    ai: {
      provider: 'openai',
      apiKey: 'sk-proj-DemoContaturRJKey_448822001199',
      model: 'gpt-4o-mini',
      temperature: 0.2,
      systemPrompt: `Você é o Auditor de Sentimento da CONTATUR RIO. Avalie e-mails com ênfase na legislação tributária do RJ e oportunidades comerciais.`,
      minConfidenceScore: 70,
      enableCommercialDetection: true,
      enableQualityAuditing: true,
      enableOcrAndAudioTranscription: true,
      lastTestedAt: '2026-08-18T13:22:00Z',
    },
    alertChannels: {
      emailNotifications: {
        enabled: true,
        destinationEmails: ['renata.gerencia@contatur-rio.com.br'],
        sendOnCritical: true,
        sendOnHigh: true,
        sendOnCommercialLead: true,
      },
      msTeams: {
        enabled: true,
        webhookUrl: 'https://contatur.webhook.office.com/webhookb2/rj-incidentes',
        sendOnCritical: true,
        sendOnHigh: false,
        sendOnCommercialLead: true,
      },
      whatsapp: {
        enabled: true,
        apiEndpoint: 'https://api.z-api.io/instances/contatur-rj/token/sendMessage',
        apiToken: '••••••••••••••••••••••••••••••••',
        destinationNumbers: ['5521988887777'],
        sendOnCritical: true,
        sendOnHigh: false,
      },
      discord: { enabled: false, webhookUrl: '', sendOnCritical: false },
      telegram: { enabled: false, botToken: '', chatId: '', sendOnCritical: false },
    },
    supervisorWorkflow: {
      enabled: true,
      autoSendWelcomeEmail: false,
      welcomeEmailTemplate: `Prezado(a) {CLIENTE_NOME},\n\nSou {SUPERVISOR_NOME}, da supervisão {DEPARTAMENTO} da Contatur Rio. Assumi o protocolo #{PROTOCOLO} e estamos tratando com máxima prioridade.`,
      statusUpdateTemplate: `Prezado(a) {CLIENTE_NOME},\n\nSeu chamado #{PROTOCOLO} está em andamento com nossa equipe técnica.`,
      csatEmailTemplate: `Prezado(a) {CLIENTE_NOME},\n\nComo você avalia o atendimento da Contatur Rio no chamado #{PROTOCOLO}?`,
      escalateToDirectorHours: 2,
    },
    sgcIntegration: {
      enabled: true,
      baseUrl: 'https://sgc.grupocontaturmkp.com.br/api/external/v1',
      apiToken: 'sgc_sec_contatur_rj_8811442200',
      autoPushLeads: false,
      lastTestedAt: '2026-08-18T14:00:00Z',
      connectionStatus: 'conectado',
    },
    meetingIntegration: {
      enabled: true,
      baseUrl: 'https://meeting.grupocontaturmkp.com.br/api/external/v1',
      apiToken: 'meeting_sec_contatur_rj_445522',
      autoInjectDossierInAgenda: true,
      defaultMeetingLocation: 'Auditório Contatur Rio / Teams',
      lastTestedAt: '2026-08-18T14:00:00Z',
      connectionStatus: 'conectado',
    },
    monthlyBroadcastSettings: {
      enabled: true,
      targetAudienceProfile: 'Turismo, Hotelaria & Eventos',
      dispatchDayOfMonth: 25,
      autoDispatchWhenAllApproved: false,
      supervisors: {
        folha: { name: 'Patricia Lemos', email: 'dp@contatur-rio.com.br' },
        fiscal: { name: 'Felipe Meirelles', email: 'fiscal@contatur-rio.com.br' },
        contabil: { name: 'Rodrigo Paiva', email: 'contabil@contatur-rio.com.br' },
        legal: { name: 'Marcio Silva', email: 'legal@contatur-rio.com.br' },
      },
      approvalRequestEmailTemplate: `Prezado(a) {SUPERVISOR_NOME},\n\nRevise a proposta de Circular do setor {DEPARTAMENTO} para aprovação ou novos ajustes.`,
    },
    slaAndRules: {
      slaHoursCritical: 2,
      slaHoursHigh: 6,
      slaHoursMedium: 24,
      slaHoursLow: 48,
      autoPromoteNearFiscalDeadline: true,
      touchpointDelayHours: 48,
      blacklistKeywords: ['newsletter', 'promoção', 'no-reply'],
      priorityKeywords: ['jucerja', 'multa', 'cancelar', 'sefaz-rj', 'urgente'],
      autoIgnoreSpamAndNewsletters: true,
    },
  },
  mkp_sp: {
    tenantId: 'mkp_sp',
    email: {
      provider: 'm365',
      m365: {
        tenantId: 'mkp-sp-azure-tenant-id-7721',
        clientId: 'mkp-sp-app-client-id-3310',
        clientSecret: '••••••••••••••••••••••••••••••••',
        adminEmail: 'admin@mkpcontabil.com.br',
      },
      googleWorkspace: {
        adminEmail: 'admin@mkpcontabil.com.br',
        serviceAccountJson: '',
        delegatedSubject: '',
      },
      imap: {
        host: 'mail.mkpcontabil.com.br',
        port: 993,
        useSsl: true,
        user: 'monitoramento@mkpcontabil.com.br',
        pass: '',
      },
      syncIntervalMinutes: 5,
      monitorBoardOfDirectors: true,
      lastTestedAt: '2026-08-18T13:21:00Z',
      connectionStatus: 'conectado',
    },
    ai: {
      provider: 'gemini',
      apiKey: 'AIzaSyDemoMKPKey_991122334455',
      model: 'gemini-1.5-flash',
      temperature: 0.3,
      systemPrompt: `Você é o Auditor de Relacionamento e Qualidade da MKP SÃO PAULO. Detecte reclamações, leads comerciais e auditoria de qualidade.`,
      minConfidenceScore: 75,
      enableCommercialDetection: true,
      enableQualityAuditing: true,
      enableOcrAndAudioTranscription: true,
      lastTestedAt: '2026-08-18T13:21:00Z',
    },
    alertChannels: {
      emailNotifications: {
        enabled: true,
        destinationEmails: ['gustavo.gerencia@mkpcontabil.com.br'],
        sendOnCritical: true,
        sendOnHigh: true,
        sendOnCommercialLead: true,
      },
      msTeams: { enabled: false, webhookUrl: '', sendOnCritical: false, sendOnHigh: false, sendOnCommercialLead: false },
      whatsapp: {
        enabled: true,
        apiEndpoint: 'https://api.z-api.io/instances/mkp-sp/token/sendMessage',
        apiToken: '••••••••••••••••••••••••••••••••',
        destinationNumbers: ['5511955554444'],
        sendOnCritical: true,
        sendOnHigh: true,
      },
      discord: { enabled: false, webhookUrl: '', sendOnCritical: false },
      telegram: { enabled: false, botToken: '', chatId: '', sendOnCritical: false },
    },
    supervisorWorkflow: {
      enabled: true,
      autoSendWelcomeEmail: false,
      welcomeEmailTemplate: `Prezado(a) {CLIENTE_NOME},\n\nSou {SUPERVISOR_NOME}, da supervisão MKP São Paulo. Assumi o protocolo #{PROTOCOLO} e estamos acompanhando sua solicitação pessoalmente.`,
      statusUpdateTemplate: `Prezado(a) {CLIENTE_NOME},\n\nAtualização sobre o chamado #{PROTOCOLO}: estamos finalizando os ajustes necessários.`,
      csatEmailTemplate: `Prezado(a) {CLIENTE_NOME},\n\nComo foi sua experiência com a resolução do chamado #{PROTOCOLO}?`,
      escalateToDirectorHours: 2,
    },
    sgcIntegration: {
      enabled: true,
      baseUrl: 'https://sgc.grupocontaturmkp.com.br/api/external/v1',
      apiToken: 'sgc_sec_mkp_sp_3399110022',
      autoPushLeads: false,
      lastTestedAt: '2026-08-18T14:00:00Z',
      connectionStatus: 'conectado',
    },
    meetingIntegration: {
      enabled: true,
      baseUrl: 'https://meeting.grupocontaturmkp.com.br/api/external/v1',
      apiToken: 'meeting_sec_mkp_sp_998833',
      autoInjectDossierInAgenda: true,
      defaultMeetingLocation: 'Sala Executiva MKP SP',
      lastTestedAt: '2026-08-18T14:00:00Z',
      connectionStatus: 'conectado',
    },
    monthlyBroadcastSettings: {
      enabled: true,
      targetAudienceProfile: 'Indústria, Comércio Geral & Logística',
      dispatchDayOfMonth: 25,
      autoDispatchWhenAllApproved: false,
      supervisors: {
        folha: { name: 'Silvia Ramos', email: 'dp@mkpcontabil.com.br' },
        fiscal: { name: 'Gustavo Paes', email: 'fiscal@mkpcontabil.com.br' },
        contabil: { name: 'Arnaldo Antunes', email: 'contabil@mkpcontabil.com.br' },
        legal: { name: 'Beatriz Costa', email: 'legal@mkpcontabil.com.br' },
      },
      approvalRequestEmailTemplate: `Prezado(a) {SUPERVISOR_NOME},\n\nRevise a proposta de Circular Técnica MKP para o setor {DEPARTAMENTO}.`,
    },
    slaAndRules: {
      slaHoursCritical: 2,
      slaHoursHigh: 4,
      slaHoursMedium: 12,
      slaHoursLow: 24,
      autoPromoteNearFiscalDeadline: true,
      touchpointDelayHours: 48,
      blacklistKeywords: ['newsletter', 'promoção', 'no-reply'],
      priorityKeywords: ['das', 'simples nacional', 'erro', 'urgente', 'cancelar'],
      autoIgnoreSpamAndNewsletters: true,
    },
  },
};

// ----------------------------------------------------
// MOCKS INICIAIS DAS CIRCULARES MENSAIS MULTISSETORIAIS
// ----------------------------------------------------
export const INITIAL_MONTHLY_BROADCASTS: import('../types').MonthlyBroadcastCircular[] = [
  {
    id: 'circ_sp_2026_08',
    tenantId: 'contatur_sp',
    editionMonth: '2026-08',
    title: 'Circular Informativa & Legislativa &bull; Edição Especial Turismo & Serviços',
    targetAudienceProfile: 'Turismo, Hotelaria & Eventos',
    overallStatus: 'AGUARDANDO_SUPERVISORES',
    scheduledDispatchDate: '2026-08-25',
    totalRecipientsCount: 142,
    createdAt: '2026-08-15T08:00:00Z',
    sections: {
      folha: {
        id: 'sec_sp_folha',
        department: 'FOLHA',
        departmentLabel: 'Departamento Pessoal & RH',
        supervisorName: 'Lucas Brandão',
        supervisorEmail: 'lucas.dp@contatur.com.br',
        title: 'Convenção Coletiva de Turismo & Nova Regra de Gorjetas em Eventos',
        summary: 'Orientações práticas sobre a homologação do aditivo salarial 2026 do sindicato de turismo e o correto lançamento do rateio de gorjetas na folha.',
        fullBodyText: 'Informamos a todos os clientes do segmento de agências e eventos que foi homologado o novo termo aditivo da convenção coletiva. Destacamos a obrigatoriedade do envio das planilhas de rateio de gorjetas e adicionais até o dia 22 de cada mês para processamento seguro no eSocial e FGTS Digital.',
        actionableRecommendation: 'Revisar a tabela de cargos e enviar o espelho de ponto até o dia 22/08 para evitar multas de fechamento.',
        status: 'APROVADO',
        versionNumber: 1,
        approvedAt: '2026-08-16T14:30:00Z',
      },
      fiscal: {
        id: 'sec_sp_fiscal',
        department: 'FISCAL',
        departmentLabel: 'Setor Tributário & Fiscal',
        supervisorName: 'Mariana Souza',
        supervisorEmail: 'mariana.fiscal@contatur.com.br',
        title: 'Manutenção dos Benefícios do PERSE e Tributação de Comissões de Viagens',
        summary: 'Análise da Receita Federal sobre o teto de faturamento do PERSE e a segregação de receitas próprias vs. comissões de intermediação turística.',
        fullBodyText: 'A Receita Federal publicou instrução normativa pacificando a tributação de agências de turismo. O valor repassado a companhias aéreas e hotéis não compõe a base de cálculo do PIS/COFINS, devendo o imposto incidir estritamente sobre a comissão líquida auferida. Clientes enquadrados no PERSE devem atentar para a entrega da declaração de habilitação prévia.',
        actionableRecommendation: 'Separar no extrato bancário as entradas de repasses de terceiros das comissões líquidas da agência.',
        status: 'PENDENTE_APROVACAO',
        versionNumber: 1,
      },
      contabil: {
        id: 'sec_sp_contabil',
        department: 'CONTABIL',
        departmentLabel: 'Setor Contábil & Patrimonial',
        supervisorName: 'Julio Cesar',
        supervisorEmail: 'julio.contabil@contatur.com.br',
        title: 'Conciliação de Cartões Corporativos e Moedas Estrangeiras no Fechamento',
        summary: 'Padrão contábil para registro de variações cambiais ativas e passivas em pacotes internacionais.',
        fullBodyText: 'Com a volatilidade cambial recente, reforçamos que os fechamentos contábeis de pacotes turísticos com fornecedores estrangeiros exigem o extrato de fechamento de câmbio para reconhecimento da variação cambial líquida dedutível no IRPJ.',
        actionableRecommendation: 'Encaminhar os contratos de câmbio junto com os extratos bancários mensais.',
        status: 'APROVADO',
        versionNumber: 1,
        approvedAt: '2026-08-16T16:00:00Z',
      },
      legal: {
        id: 'sec_sp_legal',
        department: 'LEGAL',
        departmentLabel: 'Societário & Legalização',
        supervisorName: 'Renata Castro',
        supervisorEmail: 'societario@contatur.com.br',
        title: 'Renovação Obrigatória do CADASTUR e Alvarás Turísticos de SP',
        summary: 'Calendário de renovação de certificados CADASTUR perante o Ministério do Turismo.',
        fullBodyText: 'Lembramos que o CADASTUR é requisito indispensável para a fruição de alíquotas reduzidas e participação em licitações públicas de passagens e eventos. Nossa equipe societária já iniciou a triagem dos certificados com vencimento no 2º semestre.',
        actionableRecommendation: 'Verificar a data de validade no verso do seu certificado CADASTUR.',
        status: 'PENDENTE_APROVACAO',
        versionNumber: 1,
      },
    },
  },
  {
    id: 'circ_mkp_2026_08',
    tenantId: 'mkp_sp',
    editionMonth: '2026-08',
    title: 'Circular Tributária & Trabalhista &bull; Edição Indústria, Comércio & Logística',
    targetAudienceProfile: 'Indústria, Comércio Geral & Logística',
    overallStatus: 'AGUARDANDO_SUPERVISORES',
    scheduledDispatchDate: '2026-08-25',
    totalRecipientsCount: 98,
    createdAt: '2026-08-15T08:00:00Z',
    sections: {
      folha: {
        id: 'sec_mkp_folha',
        department: 'FOLHA',
        departmentLabel: 'Departamento Pessoal & RH',
        supervisorName: 'Silvia Ramos',
        supervisorEmail: 'dp@mkpcontabil.com.br',
        title: 'Regras de SST e Laudos de Insalubridade no eSocial para Indústrias',
        summary: 'Exigência dos eventos S-2210, S-2220 e S-2240 e prevenção de multas automáticas no PPP Eletrônico.',
        fullBodyText: 'A fiscalização digital do trabalho está cruzando os laudos LTCAT e PGR com a folha de pagamento. Fábricas e distribuidoras com ambientes ruidosos ou manuseio químico devem manter os ASOs rigorosamente atualizados.',
        actionableRecommendation: 'Validar com sua assessoria de medicina do trabalho se todos os exames periódicos foram transmitidos.',
        status: 'APROVADO',
        versionNumber: 1,
        approvedAt: '2026-08-17T10:00:00Z',
      },
      fiscal: {
        id: 'sec_mkp_fiscal',
        department: 'FISCAL',
        departmentLabel: 'Setor Tributário & Fiscal',
        supervisorName: 'Gustavo Paes',
        supervisorEmail: 'fiscal@mkpcontabil.com.br',
        title: 'Reforma Tributária: Créditos Financeiros de IBS/CBS na Compra de Insumos Industriais',
        summary: 'Transição das regras de creditamento e fim da cumulatividade nos insumos e energia fabril.',
        fullBodyText: 'A regulamentação da Reforma Tributária traz grandes vantagens para a indústria: o crédito integral de IBS e CBS sobre toda e qualquer despesa operacional e insumo com nota fiscal, superando as restrições históricas do PIS/COFINS.',
        actionableRecommendation: 'Mapear os fornecedores de matéria-prima e revisar as notas de entrada.',
        status: 'APROVADO',
        versionNumber: 1,
        approvedAt: '2026-08-17T11:00:00Z',
      },
      contabil: {
        id: 'sec_mkp_contabil',
        department: 'CONTABIL',
        departmentLabel: 'Setor Contábil & Patrimonial',
        supervisorName: 'Arnaldo Antunes',
        supervisorEmail: 'contabil@mkpcontabil.com.br',
        title: 'Controle de Estoque no Bloco K e Depreciação Acelerada de Maquinário',
        summary: 'Alinhamento do inventário físico fabril com a contabilidade para fins de IRPJ no Lucro Real.',
        fullBodyText: 'A contabilidade de indústrias no Lucro Real pode usufruir da depreciação acelerada incentivada para novas máquinas industriais adquiridas em 2026, reduzindo substancialmente a base de cálculo do IRPJ e da CSLL.',
        actionableRecommendation: 'Enviar a relação de notas fiscais de bens do ativo imobilizado adquiridos no trimestre.',
        status: 'PENDENTE_APROVACAO',
        versionNumber: 1,
      },
      legal: {
        id: 'sec_mkp_legal',
        department: 'LEGAL',
        departmentLabel: 'Societário & Legalização',
        supervisorName: 'Beatriz Costa',
        supervisorEmail: 'legal@mkpcontabil.com.br',
        title: 'Licenças da CETESB, AVCB e Inscrição em Postos Fiscais de SP',
        summary: 'Monitoramento da validade de licenças ambientais e de operação para galpões industriais.',
        fullBodyText: 'A renovação das licenças de funcionamento perante a CETESB e Corpo de Bombeiros deve ser protocolada com no mínimo 120 dias de antecedência para evitar a suspensão da Inscrição Estadual.',
        actionableRecommendation: 'Conferir o prazo de validade do AVCB e da licença de operação.',
        status: 'APROVADO',
        versionNumber: 1,
        approvedAt: '2026-08-17T15:00:00Z',
      },
    },
  },
];

// ----------------------------------------------------
// MOCKS DE CARGA DE TRABALHO & BURNOUT DA EQUIPE
// ----------------------------------------------------
export const INITIAL_TEAM_WORKLOAD: import('../types').TeamWorkloadMember[] = [
  {
    id: 'wk_1',
    tenantId: 'contatur_sp',
    analystName: 'Mariana Souza',
    analystEmail: 'mariana.fiscal@contatur.com.br',
    department: 'FISCAL',
    activeAssignedClientsCount: 42,
    emailsReceivedThisMonth: 618,
    averageResponseTimeHours: 1.4,
    burnoutRiskLevel: 'ALTO',
    isOverloaded: true,
    rebalancingRecommendation: 'Transferir 6 clientes de Lucro Presumido para o Analista Júnior para equilibrar a quinzena do dia 15 a 20.',
  },
  {
    id: 'wk_2',
    tenantId: 'contatur_sp',
    analystName: 'Lucas Brandão',
    analystEmail: 'lucas.dp@contatur.com.br',
    department: 'FOLHA',
    activeAssignedClientsCount: 38,
    emailsReceivedThisMonth: 540,
    averageResponseTimeHours: 1.8,
    burnoutRiskLevel: 'CRITICO_SOBRECARGA',
    isOverloaded: true,
    rebalancingRecommendation: 'Dividir a conferência de espelhos de ponto da quinzena com o estagiário de DP.',
  },
  {
    id: 'wk_3',
    tenantId: 'contatur_sp',
    analystName: 'Julio Cesar',
    analystEmail: 'julio.contabil@contatur.com.br',
    department: 'CONTABIL',
    activeAssignedClientsCount: 28,
    emailsReceivedThisMonth: 210,
    averageResponseTimeHours: 2.5,
    burnoutRiskLevel: 'BAIXO',
    isOverloaded: false,
  },
  {
    id: 'wk_4',
    tenantId: 'contatur_sp',
    analystName: 'Renata Castro',
    analystEmail: 'societario@contatur.com.br',
    department: 'LEGAL',
    activeAssignedClientsCount: 22,
    emailsReceivedThisMonth: 185,
    averageResponseTimeHours: 2.1,
    burnoutRiskLevel: 'MODERADO',
    isOverloaded: false,
  },
];

// ----------------------------------------------------
// MOCKS DE DIAGNÓSTICO POR DEPARTAMENTO
// ----------------------------------------------------
export const INITIAL_DEPARTMENT_METRICS: Record<TenantId, import('../types').DepartmentMetric[]> = {
  contatur_sp: [
    {
      department: 'FISCAL',
      departmentLabel: 'Setor Fiscal & Tributário',
      avgResponseTimeHours: 1.4,
      csatAverageRating: 4.6,
      totalIncidentsResolved: 48,
      complaintsRate: 4.2,
      praisesCount: 14,
      slaComplianceRate: 97.5,
    },
    {
      department: 'FOLHA',
      departmentLabel: 'Departamento Pessoal & Folha',
      avgResponseTimeHours: 1.8,
      csatAverageRating: 4.4,
      totalIncidentsResolved: 35,
      complaintsRate: 5.8,
      praisesCount: 11,
      slaComplianceRate: 94.2,
    },
    {
      department: 'CONTABIL',
      departmentLabel: 'Setor Contábil',
      avgResponseTimeHours: 2.5,
      csatAverageRating: 4.8,
      totalIncidentsResolved: 18,
      complaintsRate: 1.5,
      praisesCount: 9,
      slaComplianceRate: 98.0,
    },
    {
      department: 'LEGAL',
      departmentLabel: 'Societário & Legalização',
      avgResponseTimeHours: 2.1,
      csatAverageRating: 4.7,
      totalIncidentsResolved: 12,
      complaintsRate: 2.0,
      praisesCount: 7,
      slaComplianceRate: 96.0,
    },
  ],
  contatur_rj: [
    {
      department: 'FISCAL',
      departmentLabel: 'Setor Fiscal RJ',
      avgResponseTimeHours: 1.9,
      csatAverageRating: 4.5,
      totalIncidentsResolved: 26,
      complaintsRate: 4.8,
      praisesCount: 8,
      slaComplianceRate: 95.0,
    },
    {
      department: 'FOLHA',
      departmentLabel: 'Departamento Pessoal RJ',
      avgResponseTimeHours: 2.2,
      csatAverageRating: 4.3,
      totalIncidentsResolved: 19,
      complaintsRate: 6.0,
      praisesCount: 5,
      slaComplianceRate: 93.0,
    },
    {
      department: 'CONTABIL',
      departmentLabel: 'Setor Contábil RJ',
      avgResponseTimeHours: 2.4,
      csatAverageRating: 4.7,
      totalIncidentsResolved: 14,
      complaintsRate: 2.1,
      praisesCount: 6,
      slaComplianceRate: 97.0,
    },
    {
      department: 'LEGAL',
      departmentLabel: 'Societário RJ',
      avgResponseTimeHours: 2.6,
      csatAverageRating: 4.6,
      totalIncidentsResolved: 9,
      complaintsRate: 3.0,
      praisesCount: 4,
      slaComplianceRate: 94.0,
    },
  ],
  mkp_sp: [
    {
      department: 'FISCAL',
      departmentLabel: 'Setor Fiscal MKP',
      avgResponseTimeHours: 1.6,
      csatAverageRating: 4.7,
      totalIncidentsResolved: 22,
      complaintsRate: 3.5,
      praisesCount: 9,
      slaComplianceRate: 98.0,
    },
    {
      department: 'FOLHA',
      departmentLabel: 'Departamento Pessoal MKP',
      avgResponseTimeHours: 1.7,
      csatAverageRating: 4.6,
      totalIncidentsResolved: 16,
      complaintsRate: 4.0,
      praisesCount: 6,
      slaComplianceRate: 96.5,
    },
    {
      department: 'CONTABIL',
      departmentLabel: 'Setor Contábil MKP',
      avgResponseTimeHours: 2.1,
      csatAverageRating: 4.9,
      totalIncidentsResolved: 15,
      complaintsRate: 1.2,
      praisesCount: 8,
      slaComplianceRate: 99.0,
    },
    {
      department: 'LEGAL',
      departmentLabel: 'Societário MKP',
      avgResponseTimeHours: 2.0,
      csatAverageRating: 4.8,
      totalIncidentsResolved: 8,
      complaintsRate: 2.2,
      praisesCount: 5,
      slaComplianceRate: 97.0,
    },
  ],
};

