import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const TENANTS = [
  {
    id: 'contatur_sp',
    name: 'Contatur São Paulo',
    slug: 'contatur-sp',
    city: 'São Paulo',
    cnpj: '12.345.678/0001-90',
    activeClientsCount: 145,
    monthlyRevenueTotal: 480000.0,
  },
  {
    id: 'contatur_rio',
    name: 'Contatur Rio',
    slug: 'contatur-rio',
    city: 'Rio de Janeiro',
    cnpj: '12.345.678/0002-71',
    activeClientsCount: 98,
    monthlyRevenueTotal: 310000.0,
  },
  {
    id: 'mkp_sp',
    name: 'MKP São Paulo',
    slug: 'mkp-sp',
    city: 'São Paulo',
    cnpj: '98.765.432/0001-11',
    activeClientsCount: 72,
    monthlyRevenueTotal: 260000.0,
  },
];

const INITIAL_MAILBOXES = [
  {
    id: 'box_001',
    tenantId: 'contatur_sp',
    name: 'Fiscal e Tributos SP',
    email: 'fiscal@contatur.com.br',
    department: 'FISCAL',
    protocol: 'GRAPH_API',
    active: true,
    unreadCount: 4,
    syncIntervalMin: 5,
  },
  {
    id: 'box_002',
    tenantId: 'contatur_sp',
    name: 'Departamento Pessoal SP',
    email: 'dp@contatur.com.br',
    department: 'DP',
    protocol: 'GRAPH_API',
    active: true,
    unreadCount: 2,
    syncIntervalMin: 5,
  },
  {
    id: 'box_003',
    tenantId: 'contatur_rio',
    name: 'Atendimento Geral Rio',
    email: 'contato.rio@contatur.com.br',
    department: 'ATENDIMENTO',
    protocol: 'GRAPH_API',
    active: true,
    unreadCount: 1,
    syncIntervalMin: 5,
  },
  {
    id: 'box_004',
    tenantId: 'mkp_sp',
    name: 'Operações MKP SP',
    email: 'operacoes@mkp.com.br',
    department: 'CONTABIL',
    protocol: 'GRAPH_API',
    active: true,
    unreadCount: 3,
    syncIntervalMin: 5,
  },
];

const INITIAL_CONFIGS = [
  {
    tenantId: 'contatur_sp',
    aiSensitivity: 'ALTA',
    quietHoursStart: '19:00',
    quietHoursEnd: '07:30',
    enableAutoDraft: true,
    notifyOnCriticalSentiment: true,
    sgcIntegration: { enabled: true, baseUrl: 'https://sgc.grupocontaturmkp.com.br/api/external/v1', autoPushLeads: false },
    meetingIntegration: { enabled: true, baseUrl: 'https://meeting.grupocontaturmkp.com.br/api/external/v1', autoInjectDossierInAgenda: true },
    supervisorWorkflow: { autoAssignToSupervisorOnCritical: true, escalationHoursLimit: 2 },
    monthlyBroadcastSettings: { autoGenerateDayOfMonth: 1, requireAllSupervisorsApproval: true },
  },
  {
    tenantId: 'contatur_rio',
    aiSensitivity: 'MODERADA',
    quietHoursStart: '18:30',
    quietHoursEnd: '08:00',
    enableAutoDraft: true,
    notifyOnCriticalSentiment: true,
    sgcIntegration: { enabled: true, baseUrl: 'https://sgc.grupocontaturmkp.com.br/api/external/v1', autoPushLeads: false },
    meetingIntegration: { enabled: true, baseUrl: 'https://meeting.grupocontaturmkp.com.br/api/external/v1', autoInjectDossierInAgenda: true },
    supervisorWorkflow: { autoAssignToSupervisorOnCritical: true, escalationHoursLimit: 4 },
    monthlyBroadcastSettings: { autoGenerateDayOfMonth: 1, requireAllSupervisorsApproval: true },
  },
  {
    tenantId: 'mkp_sp',
    aiSensitivity: 'MODERADA',
    quietHoursStart: '19:00',
    quietHoursEnd: '07:30',
    enableAutoDraft: true,
    notifyOnCriticalSentiment: true,
    sgcIntegration: { enabled: true, baseUrl: 'https://sgc.grupocontaturmkp.com.br/api/external/v1', autoPushLeads: false },
    meetingIntegration: { enabled: true, baseUrl: 'https://meeting.grupocontaturmkp.com.br/api/external/v1', autoInjectDossierInAgenda: true },
    supervisorWorkflow: { autoAssignToSupervisorOnCritical: true, escalationHoursLimit: 3 },
    monthlyBroadcastSettings: { autoGenerateDayOfMonth: 1, requireAllSupervisorsApproval: true },
  },
];

export async function seedDatabase() {
  console.log('[Seed] Iniciando população do banco de dados multi-tenant Sentinela...');

  for (const t of TENANTS) {
    await prisma.tenant.upsert({
      where: { id: t.id },
      update: t,
      create: t,
    });
  }
  console.log('✓ Tenants cadastrados (Contatur SP, Contatur Rio, MKP SP)');

  for (const cfg of INITIAL_CONFIGS) {
    await prisma.tenantConfig.upsert({
      where: { tenantId: cfg.tenantId },
      update: cfg,
      create: cfg,
    });
  }
  console.log('✓ Configurações por escritório cadastradas');

  // Usuários NÃO são semeados: o primeiro SuperAdmin nasce por
  // POST /api/auth/bootstrap (BOOTSTRAP_SECRET) e os demais pela tela de
  // Usuários. Semear usuários sem senha só bloquearia o bootstrap.

  for (const mb of INITIAL_MAILBOXES) {
    await prisma.monitoredMailbox.upsert({
      where: { id: mb.id },
      update: mb,
      create: mb,
    });
  }
  console.log('✓ Caixas postais cadastradas');

  console.log('[Seed] População concluída com sucesso!');
}

if (process.argv[1]?.includes('seed')) {
  seedDatabase()
    .catch((err) => {
      console.error('[Seed Error]', err);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}
